// The plain renderer's Cloudflare Pages worker, written only when the wiki has restricted folders.
//
// It serves restricted folders' sidebar groups and search entries at /private/nav.json, and only
// to readers whose Cloudflare Access sign-in token verifies and whose email is on the folder's
// allow list (the "allow:" lines in its RESTRICTED.txt). Anyone else gets 404. It runs behind the
// wiki-wide Access rules, so the reader's token is already there; a separate Access rule on
// /private would need a second sign-in that a background request cannot complete.
// The pages themselves are guarded by path-scoped Access apps on the folder, set up by hand.
// The worker also applies the redirects, whichever way Pages treats _redirects when a worker is present.
export function workerSource(redirectMap, privateGroups, access) {
  return `// Generated by scripts/wiki-build (render.mjs). Do not edit; rebuild the wiki instead.
const REDIRECTS = ${JSON.stringify(redirectMap)};
const PRIVATE = ${JSON.stringify(privateGroups)};
const ACCESS = ${JSON.stringify({ team: access.team, auds: access.auds })};
let certs = null;

const bytes = s => Uint8Array.from(atob(s.replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(s.length / 4) * 4, '=')), c => c.charCodeAt(0));
const decode = s => JSON.parse(new TextDecoder().decode(bytes(s)));

// The email in the reader's Access token, only if the token is signed by our Access
// team, issued for this wiki, and unexpired.
async function verifiedEmail(request) {
  const token = request.headers.get('cf-access-jwt-assertion');
  const [h, p, sig] = (token || '').split('.');
  if (!sig) return null;
  const header = decode(h);
  const payload = decode(p);
  const auds = [].concat(payload.aud || []);
  if (payload.iss !== ACCESS.team || !auds.some(a => ACCESS.auds.includes(a)) || !(payload.exp * 1000 > Date.now())) return null;
  for (let attempt = 0; attempt < 2; attempt++) {
    if (!certs || attempt) certs = (await (await fetch(ACCESS.team + '/cdn-cgi/access/certs')).json()).keys;
    const jwk = certs.find(k => k.kid === header.kid);
    if (!jwk) continue;
    const key = await crypto.subtle.importKey('jwk', jwk, { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' }, false, ['verify']);
    const ok = await crypto.subtle.verify('RSASSA-PKCS1-v1_5', key, bytes(sig), new TextEncoder().encode(h + '.' + p));
    return ok ? String(payload.email || '').toLowerCase() : null;
  }
  return null;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const to = REDIRECTS[url.pathname];
    if (to) return Response.redirect(new URL(to, url).toString(), 301);
    if (url.pathname === '/private/nav.json') {
      const email = await verifiedEmail(request).catch(() => null);
      const mine = email ? PRIVATE.filter(g => g.allow.includes(email)) : [];
      if (!mine.length) return new Response('Not found', { status: 404 });
      return new Response(JSON.stringify({ groups: mine.map(g => g.group), search: mine.flatMap(g => g.search) }), {
        headers: { 'content-type': 'application/json', 'cache-control': 'private, no-store' },
      });
    }
    if (url.pathname.startsWith('/private/')) return new Response('Not found', { status: 404 });
    return env.ASSETS.fetch(request);
  },
};
`;
}
